appConfig:
  PORT: 3000
  API_URL: "<path:secret/data/test-1/api/config#app_url>"
  MONGODB_URI: "<path:secret/data/test-1/api/config#mongo_uri>"
  REDIS_URI: "<path:secret/data/test-1/api/config#redis_uri>"
  AMQP_URI: "<path:secret/data/test-1/api/config#amqp_uri>"
  API_VERSION: "2024-10"
  SHOPIFY_THEME_EXTENSION_ID: "<path:secret/data/test-1/api/config#theme_extension_id>"
  AWS_BUCKET_NAME: "<path:secret/data/test-1/api/config#aws_bucket_name>"
  AWS_BUCKET_REGION: "<path:secret/data/test-1/api/config#aws_bucket_region>"
  AWS_ACCESS_KEY: "<path:secret/data/test-1/api/config#aws_access_key>"
  AWS_SECRET_KEY: "<path:secret/data/test-1/api/config#aws_secret_key>"

appSecret:
  SHOPIFY_API_KEY: "<path:secret/data/test-1/api/secret#shopify_api_key>"
  SHOPIFY_API_SECRET: "<path:secret/data/test-1/api/secret#shopify_api_secret>"
  PROXY_CHECK_API_KEY: "<path:secret/data/test-1/api/secret#proxy_check_api_key>"