apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.appConfig }}
  {{ $key }}: "{{ $value }}"
{{- end }}