appConfig:
  PORT: 3000
  API_URL: ""
  MONGODB_URI: ""
  REDIS_URI: ""
  AMQP_URI: ""
  DB_NAME: ""
  API_VERSION: ""
  SHOPIFY_THEME_EXTENSION_ID: ""
  AWS_BUCKET_NAME: ""
  AWS_BUCKET_REGION: ""
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""

appSecret:
  SHOPIFY_API_KEY: ""
  SHOPIFY_API_SECRET: ""
  PROXY_CHECK_API_KEY: ""