apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical-token-reviewer
  namespace: {{ .Release.Namespace }}

---

apiVersion: v1
kind: Secret
metadata:
  name: infisical-token-reviewer-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: "infisical-token-reviewer"
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infisical-token-reviewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: infisical-token-reviewer
    namespace: {{ .Release.Namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.infisical.serviceAccountName }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.infisical.serviceAccountName }}-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: "{{ .Values.infisical.serviceAccountName }}"
type: kubernetes.io/service-account-token
