appConfig:
  VITE_SHOPIFY_APP_URL: "<path:secret/data/test-1/cms/config#cms_url>"
  VITE_PORT: 3000
  VITE_API_URL: "<path:secret/data/test-1/cms/config#api_url>"
  VITE_APP_EMBED_NAME: "blocker-script"
  VITE_CRISP_CHAT_ID: "<path:secret/data/test-1/cms/config#crisp_chat_id>"
  PORT: 3000
  SHOPIFY_APP_URL: "<path:secret/data/test-1/cms/config#cms_url>"

appSecret:
  VITE_SHOPIFY_API_KEY: <path:secret/data/test-1/cms/secret#shopify_api_key>
  VITE_SHOPIFY_API_SECRET_KEY: <path:secret/data/test-1/cms/secret#shopify_api_secret>
  SHOPIFY_API_KEY: "<path:secret/data/test-1/cms/secret#shopify_api_key>"
  SHOPIFY_API_SECRET: "<path:secret/data/test-1/cms/secret#shopify_api_secret>"