image:
  repository: quyensatoru/blocker_cms
  tag: 1.1.0
  pullPolicy: Always

replicaCount: 1

service:
  type: NodePort
  port: 80
  targetPort: 3000

configmap:
  enabled: false

secret:
  enabled: true

ingress:
  enabled: false
  className: nginx
  host: 80
  tls: false
  tlsSecret: ""