image:
  repository: quyensatoru/blocker_api
  tag: 1.0.1
  pullPolicy: Always

replicaCount: 1

configmap:
  enabled: false
appConfig:

secret:
  enabled: true
appSecret:

service:
  type: NodePort
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: x.mida-app.io
  tls: false
  tlsSecret: ""

rabbitmq:
  image:
    registry: docker.io
    repository: bitnamilegacy/rabbitmq
    tag: "4.1.3-debian-12-r1"
  auth:
    username: dev
    password: Dev1234567
  persistence:
    enabled: false
  service:
    port: 5672

redis:
  image:
    repository: bitnamilegacy/redis
    tag: "8.2.1-debian-12-r0"
  auth:
    enabled: false
  architecture: standalone
  master:
    persistence:
      enabled: false

mongodb:
  image:
    repository: bitnamilegacy/mongodb
    tag: "7.0.12"
  volumePermissions:
    enabled: true
    image:
      repository: bitnamilegacy/mongodb
      tag: "7.0.12"
  auth:
    enabled: false
  persistence:
    enabled: false
  service:
    port: 27017